syntax = "proto3";

package user.v1;

option csharp_namespace = "SecretProject.Data.Contracts.User";

service UserService 
{
    rpc GetUserInformation(GetUserInformationRequest) returns (GetUserInformationResponse);
    rpc ChangeUserStatus(ChangeUserStatusRequest) returns (ChangeUserStatusResponse);
    rpc GetFriendRequests(GetFriendRequestsRequest) returns (GetFriendRequestsResponse);
    rpc GetFriends(GetFriendsRequest) returns (GetFriendsResponse);
    rpc ChangeUserInformation(ChangeUserInformationRequest) returns (ChangeUserInformationResponse);
    rpc ChangeMicrophoneState(ChangeMicrophoneStateRequest) returns (ChangeMicrophoneStateResponse);
    rpc ChangeHeadphonesState(ChangeHeadphonesStateRequest) returns (ChangeHeadphonesStateResponse);
}

message ChangeHeadphonesStateRequest
{
    string id = 1;
}

message ChangeHeadphonesStateResponse
{
    bool IsHeadphonesMuted = 1;
}

message ChangeMicrophoneStateRequest
{
    string id = 1;
}

message ChangeMicrophoneStateResponse
{
    bool IsMicrophoneMuted = 1;
}

message ChangeUserInformationRequest
{
    string userId = 1;
    bytes avatar = 2;
    string name = 3;
}

message ChangeUserInformationResponse
{

}

message GetUserInformationRequest 
{
    string id = 1;
}

message GetUserInformationResponse 
{
    UserDto user = 1;
}

message ChangeUserStatusRequest
{
    string status = 1;
    string userId = 2;
}

message ChangeUserStatusResponse
{
    bool status = 1;
}

message GetFriendRequestsRequest
{
    string userId = 1;
}

message GetFriendRequestsResponse
{
    repeated UserDto users = 1;
}

message GetFriendsRequest
{
    string id = 1;
}

message GetFriendsResponse
{
    repeated UserDto users = 1;
}

message UserDto
{
    string id = 1;
    string name = 2;
    string email = 3;
    string avatar = 4;
    string status = 5;
    SoundConnectionState soundState = 6;
}

message SoundConnectionState
{
    bool IsMicrophoneMuted = 1;
    bool IsHeadphonesMuted = 2;
}
