// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecretProject.Platform.Data.DataStore.Context;

#nullable disable

namespace SecretProject.Platform.Data.Migrations.ChannelDb
{
    [DbContext(typeof(ChannelDbContext))]
    partial class ChannelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("channel")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Entities.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChannelAvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("Channels", "channel");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHeadphonesMuted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMicrophoneMuted")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", "channel");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.ChannelFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelMessageId")
                        .IsUnique();

                    b.ToTable("ChannelFiles", "channel");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.ChannelMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ChannelId");

                    b.ToTable("ChannelMessages", "channel");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.ChannelUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ChannelId");

                    b.HasIndex("ChannelId");

                    b.ToTable("ChannelUsers", "channel");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("Files", "channel");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.Friendship", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationUserId1")
                        .HasColumnType("uuid");

                    b.Property<string>("FriendId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ApplicationUserId1");

                    b.ToTable("Friendship", "channel");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationUserId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReciverId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RepliedId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RepliedMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ApplicationUserId1");

                    b.HasIndex("RepliedMessageId");

                    b.ToTable("Messages", "channel");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Emotion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("MessageId");

                    b.ToTable("Reaction", "channel");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("BlockedUsers")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("MutedAudioUserIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.PrimitiveCollection<Guid[]>("MutedVideoUserIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("Id");

                    b.ToTable("Room", "channel");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.UserRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationUserId1")
                        .HasColumnType("uuid");

                    b.Property<string>("LeftUserId")
                        .HasColumnType("text");

                    b.PrimitiveCollection<Guid[]>("MutedAudioUserIds")
                        .HasColumnType("uuid[]");

                    b.PrimitiveCollection<Guid[]>("MutedVideoUserIds")
                        .HasColumnType("uuid[]");

                    b.Property<string>("RightUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ApplicationUserId1");

                    b.ToTable("UserRoom", "channel");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Entities.Channel", b =>
                {
                    b.HasOne("SecretProject.Platform.Data.DataStore.Models.ApplicationUser", "Admin")
                        .WithMany("ChannelsAdmin")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SecretProject.Platform.Data.DataStore.Models.Room", "Room")
                        .WithOne("Channel")
                        .HasForeignKey("SecretProject.Platform.Data.DataStore.Entities.Channel", "RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Admin");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.ChannelFile", b =>
                {
                    b.HasOne("SecretProject.Platform.Data.DataStore.Models.ChannelMessage", "ChannelMessage")
                        .WithOne("ChannelFile")
                        .HasForeignKey("SecretProject.Platform.Data.DataStore.Models.ChannelFile", "ChannelMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelMessage");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.ChannelMessage", b =>
                {
                    b.HasOne("SecretProject.Platform.Data.DataStore.Models.ApplicationUser", null)
                        .WithMany("ChannelMessages")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("SecretProject.Platform.Data.DataStore.Entities.Channel", "Channel")
                        .WithMany("ChannelMessages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.ChannelUser", b =>
                {
                    b.HasOne("SecretProject.Platform.Data.DataStore.Entities.Channel", "Channel")
                        .WithMany("ChannelUsers")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecretProject.Platform.Data.DataStore.Models.ApplicationUser", "User")
                        .WithMany("ChannelUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.File", b =>
                {
                    b.HasOne("SecretProject.Platform.Data.DataStore.Models.Message", "Message")
                        .WithOne("File")
                        .HasForeignKey("SecretProject.Platform.Data.DataStore.Models.File", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.Friendship", b =>
                {
                    b.HasOne("SecretProject.Platform.Data.DataStore.Models.ApplicationUser", null)
                        .WithMany("FriendOf")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("SecretProject.Platform.Data.DataStore.Models.ApplicationUser", null)
                        .WithMany("Friends")
                        .HasForeignKey("ApplicationUserId1");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.Message", b =>
                {
                    b.HasOne("SecretProject.Platform.Data.DataStore.Models.ApplicationUser", null)
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("SecretProject.Platform.Data.DataStore.Models.ApplicationUser", null)
                        .WithMany("SentMessages")
                        .HasForeignKey("ApplicationUserId1");

                    b.HasOne("SecretProject.Platform.Data.DataStore.Models.Message", "RepliedMessage")
                        .WithMany()
                        .HasForeignKey("RepliedMessageId");

                    b.Navigation("RepliedMessage");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.Reaction", b =>
                {
                    b.HasOne("SecretProject.Platform.Data.DataStore.Models.ApplicationUser", null)
                        .WithMany("Reactions")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("SecretProject.Platform.Data.DataStore.Models.Message", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.UserRoom", b =>
                {
                    b.HasOne("SecretProject.Platform.Data.DataStore.Models.ApplicationUser", null)
                        .WithMany("LeftRooms")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("SecretProject.Platform.Data.DataStore.Models.ApplicationUser", null)
                        .WithMany("RightRooms")
                        .HasForeignKey("ApplicationUserId1");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Entities.Channel", b =>
                {
                    b.Navigation("ChannelMessages");

                    b.Navigation("ChannelUsers");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.ApplicationUser", b =>
                {
                    b.Navigation("ChannelMessages");

                    b.Navigation("ChannelUsers");

                    b.Navigation("ChannelsAdmin");

                    b.Navigation("FriendOf");

                    b.Navigation("Friends");

                    b.Navigation("LeftRooms");

                    b.Navigation("Reactions");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("RightRooms");

                    b.Navigation("SentMessages");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.ChannelMessage", b =>
                {
                    b.Navigation("ChannelFile");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.Message", b =>
                {
                    b.Navigation("File")
                        .IsRequired();

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("SecretProject.Platform.Data.DataStore.Models.Room", b =>
                {
                    b.Navigation("Channel");
                });
#pragma warning restore 612, 618
        }
    }
}
