// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecretProject.Channels.Data.DataStore.Context;

#nullable disable

namespace SecretProject.Channels.Data.Migrations
{
    [DbContext(typeof(ChannelDbContext))]
    [Migration("20260510110234_InitialChannel")]
    partial class InitialChannel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("channel")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Entities.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChannelAvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("Channels", "channel");
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Models.ChannelFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelMessageId")
                        .IsUnique();

                    b.ToTable("ChannelFiles", "channel");
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Models.ChannelMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("ChannelMessages", "channel");
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Models.ChannelUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Role")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ChannelId");

                    b.HasIndex("ChannelId");

                    b.ToTable("ChannelUsers", "channel");
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Models.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("Files", "channel");
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReciverId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RepliedId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RepliedMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("RepliedMessageId");

                    b.ToTable("Messages", "channel");
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Models.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Emotion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("Reaction", "channel");
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("BlockedUsers")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("MutedAudioUserIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.PrimitiveCollection<Guid[]>("MutedVideoUserIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("Id");

                    b.ToTable("Room", "channel");
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Entities.Channel", b =>
                {
                    b.HasOne("SecretProject.Channels.Data.DataStore.Models.Room", "Room")
                        .WithOne("Channel")
                        .HasForeignKey("SecretProject.Channels.Data.DataStore.Entities.Channel", "RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Models.ChannelFile", b =>
                {
                    b.HasOne("SecretProject.Channels.Data.DataStore.Models.ChannelMessage", "ChannelMessage")
                        .WithOne("ChannelFile")
                        .HasForeignKey("SecretProject.Channels.Data.DataStore.Models.ChannelFile", "ChannelMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelMessage");
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Models.ChannelMessage", b =>
                {
                    b.HasOne("SecretProject.Channels.Data.DataStore.Entities.Channel", "Channel")
                        .WithMany("ChannelMessages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Models.ChannelUser", b =>
                {
                    b.HasOne("SecretProject.Channels.Data.DataStore.Entities.Channel", null)
                        .WithMany("ChannelUsers")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Models.File", b =>
                {
                    b.HasOne("SecretProject.Channels.Data.DataStore.Models.Message", "Message")
                        .WithOne("File")
                        .HasForeignKey("SecretProject.Channels.Data.DataStore.Models.File", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Models.Message", b =>
                {
                    b.HasOne("SecretProject.Channels.Data.DataStore.Models.Message", "RepliedMessage")
                        .WithMany()
                        .HasForeignKey("RepliedMessageId");

                    b.Navigation("RepliedMessage");
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Models.Reaction", b =>
                {
                    b.HasOne("SecretProject.Channels.Data.DataStore.Models.Message", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Entities.Channel", b =>
                {
                    b.Navigation("ChannelMessages");

                    b.Navigation("ChannelUsers");
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Models.ChannelMessage", b =>
                {
                    b.Navigation("ChannelFile");
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Models.Message", b =>
                {
                    b.Navigation("File")
                        .IsRequired();

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("SecretProject.Channels.Data.DataStore.Models.Room", b =>
                {
                    b.Navigation("Channel");
                });
#pragma warning restore 612, 618
        }
    }
}
