<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PackageId>SecretProject.Grpc.Contracts</PackageId>
		<Version>1.0.0</Version>
		<Authors>SecretProject</Authors>
		<Description>gRPC contracts for SecretProject services</Description>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Google.Protobuf" Version="3.35.0" />
		<PackageReference Include="Grpc.Core.Api" Version="2.80.0" />
		<PackageReference Include="Grpc.Tools" Version="2.81.0" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Protos\Authentication\AuthService.proto" GrpcServices="Both" />
		<Protobuf Include="Protos\Channels\ChannelService.proto" GrpcServices="Both" />
		<Protobuf Include="Protos\Email\EmailService.proto" GrpcServices="Both" />
		<Protobuf Include="Protos\User\UserService.proto" GrpcServices="Both" />
		<Protobuf Include="Protos\User\FileService.proto" GrpcServices="Both" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Protos\File\" />
	</ItemGroup>

</Project>