<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>de0d2ad8-6a7f-4d1f-8859-b2117beedb73</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.76.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SecretProject.Channels.Data\SecretProject.Channels.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\AuthService.proto" GrpcServices="Client" />
    <Protobuf Include="Protos\ChannelService.proto" GrpcServices="Server" />
  </ItemGroup>

</Project>
